version: '3.8'

services:
  nginx:
    depends_on:
        - backend
        - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - api_network
      - front_network
    image: elective-nginx:1.0
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - front_network
    image: elective-frontend:1.0
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      MONGODB_URI: mongodb://database:27017/mydatabase
    networks:
      - front_network
      - api_network
    image: elective-backend:1.0
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - api_network
networks:
  front_network:
  api_network:

volumes:
  mongodb_data:
    driver: local
