version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - front_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      MONGODB_URI: mongodb://database:27017/mydatabase
    networks:
      - front_network
      - api_network
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - api_network

networks:
  front_network:
  api_network:

volumes:
  mongodb_data:
    driver: local
